### ISSUE TITLE
Support HAPI_CurveInfo::isClosed

### ISSUE THREAD

**Issue by luxalpa** [alexxbb/hapi-rs#17]
I'm looking for a way to load a KineFX skeleton into Houdini via Engine. It seems that HAPI_CurveInfo::isClosed exists but hasn't yet been replicated here.

**Comment by alexxbb** [comment]
Pushed a fix to the main. Will do a crate release later. Meanwhile, you can pull from git directly:

```toml
[dependencies]
hapi-rs = { git = "https://github.com/alexxbb/hapi-rs.git", branch = "e287f5f" }
```
