### ISSUE TITLE
Error: Calling HAPI_StartThriftNamedPipeServer: failed

### ISSUE THREAD

**Issue by grilme99** [alexxbb/hapi-rs#19]
I am trying to use this library on an M1 Macbook, but get the following error when using the `quick_session` function with no config:

```
Error: [FAILURE]: [Engine Message]: Server error message unavailable
        0. Calling HAPI_StartThriftNamedPipeServer: failed
```

With just the following code:

```rs
use hapi_rs::session::quick_session;
use hapi_rs::Result;

fn main() -> Result<()> {
    let _session = quick_session(None)?;
    Ok(())
}
```

I'm not sure where to begin debugging the cause. Any advice? Here's some more info about my setup:

- Running Houdini version `19.5.752 M1` (from 2023-09-28)
- Running the full education license ($75), which SideFx says can run Houdini Engine

I have a `.cargo/config.toml` file with the following:

```toml
[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-Wl,-rpath,/Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Libraries",
]
```

With an `HFS` environment variable set to:

```
/Applications/Houdini/Current/Frameworks/Houdini.framework/Versions/Current/Libraries
```
